import { Mulish } from "next/font/google";
import "@/styles/globals.css";

import Navbar from "@/components/navbar";
import TopNavbar from "@/components/top-navbar";

const mulish = Mulish({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={mulish.className}>
      <body>
        <TopNavbar />
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
